# Read the Docs configuration file (see https://docs.readthedocs.io/en/stable/config-file/v2.html
# for details).

version: 2

build:
    os: ubuntu-20.04
    tools:
        python: "3.10"
    jobs:
      post_install:
        - pip install -r ${PROJECT}/test_requirements.txt
        - install_cmdstan || true  # Install cmdstan if the command is available.
