[project]
name = "gptools-util"
version = "0.1.1"
description = ""
requires-python = ">=3.8"
dependencies = [
    "numpy",
]

[tool.setuptools]
packages = {find = {namespaces = true}}
include-package-data = true
