name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  # Our tests may contain a number of stochastic elements. Setting a seed will make sure they are
  # not flaky (but also hide potential issues).
  SEED: "0"
  cmdstanVersion: "2.30.1"

jobs:
  build:
    name: Continuous Integration
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.10"
      - uses: actions/cache@v2
        with:
          path: |
            ${{ env.pythonLocation }}
            /home/runner/.cmdstan
          key: ${{ env.pythonLocation }}-${{ hashFiles('test_requirements.txt') }}-${{ env.cmdstanVersion }}
      - name: Install dependencies
        run: |
          pip install -r test_requirements.txt
          python -m cmdstanpy.install_cmdstan --version ${{ env.cmdstanVersion }}
      - name: Run the tests
        run: doit tests
      - name: Lint the code
        run: doit lint
      - name: Build the documentation
        run: doit docs
      - name: Run profiling scripts
        run: doit profile
