name: CI - R

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  cmdstanVersion: "2.31.0"

jobs:
  build:
    name: R-package
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "r-lib/actions/setup-r@v2"
        